apiVersion: v1
kind: Service
metadata:
  name: fraud-api
  namespace: fraud-detection
spec:
  type: NodePort
  selector:
    app: fraud-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800   # mapeado para localhost:8080 via kind-cluster.yaml
